# Default profile for the application--START

# The eureka configuration is used for register this micro service with Service Discovery server  
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    #non-secure-port: 0
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
#The default profile will run this micro service on following port
server:
  port: 9081

consumer:
  topic: kafkatopic
  group: testgroup1
  zookeeperhost: localhost
  consumername: consumer1
  
producer:
  serializerClass: kafka.serializer.StringEncoder
  broker: localhost
  acknowledgement: 1
  topic: kafkatopic

# Default profile for the application--END